---
title: "Week 03 Assignment 02_datasets"
author: "Justin Pickel"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    citation_package: natbib
    latex_engine: pdflatex
    template: ./../latex-templates/homework.tex
  html_document:
    df_print: paged
course: "STATS 419 Survey of Multivariate Analysis"
course-short: STATS419
instructor: Monte J. Shaffer
email: justin.pickel@wsu.edu
wsu-id: 11592048
fig_caption: true
number_sections: true
editor_options: 
  chunk_output_type: console
---
```{r,Setup, message=FALSE,warning=FALSE}
library(devtools)
local.path ="C:/_git_/WSU_STATS419_FALL2020/";
source(paste0(local.path,"functions/libraries.R"),local=T);
source( paste0(local.path,"functions/functions-imdb.R"), local=T );
```
# Martrix
Create the "rotate matrix" functions as described in lectures.  Apply to the example "myMatrix".

```{r Matrix rotation}
source( paste0(local.path,"functions/functions-matrix.R"), local=T );

myMatrix = matrix ( c (
   1, 0, 2,
   0, 3, 0,
   4, 0, 5
 ), nrow=3, byrow=T);

```
## Matrix
```{r}
rotateMatrix90(myMatrix)
```
\newpage
## Matrix
```{r}
rotateMatrix180(myMatrix)
```
## Matrix
```{r}
rotateMatrix270(myMatrix)
```

```{r}

```
