---
title: "Week 03 Assignment 02_datasets"
author: "Justin Pickel"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document:
    extra_dependencies: ["float"]
    citation_package: natbib
    latex_engine: pdflatex
    template: ./../latex-templates/homework.tex
  html_document:
    df_print: paged
course: "STATS 419 Survey of Multivariate Analysis"
course-short: STATS419
instructor: Monte J. Shaffer
email: justin.pickel@wsu.edu
fig_caption: true
number_sections: true
editor_options: 
  chunk_output_type: inline
---

```{r,Setup, message=FALSE,warning=FALSE}
library(devtools)
local.path ="C:/_git_/WSU_STATS419_FALL2020/";
source(paste0(local.path,"functions/libraries.R"),local=T);
```

```{r}
path.measure = "C:/_git_/WSU_STATS419_FALL2020/WEEK-05/datasets";
library(readxl);
#library(humanVerseWSU);

covariates = read_excel(paste0(path.measure,"/","measure.xlsx"), sheet="covariates");
panel = read_excel(paste0(path.measure,"/","measure.xlsx"), sheet="panel");

covariates = as.data.frame(covariates);
panel = as.data.frame(panel);

panel.first = panel$`person_id`[1];  # 1c2408654ef5a2fe1fc962088312266c

temp = panel[panel$`person_id` == panel.first , ];

mySide = (panel$side);
myKeys = (panel$mkey);

myJointKeys =  unique( paste0(myKeys,"-",mySide) );

## we know these are an exhaustive list of keys ...
  # covariates have 13 variables ...
  # side + jointkeys (23) + values 
tabularized.df = data.frame( matrix(NA, nrow=0, ncol=37) );
  tabularized.cols = c( colnames(covariates)[1:2], "side",myJointKeys, colnames(covariates)[3:13]);

colnames(tabularized.df) = tabularized.cols;

n.cov = dim(covariates)[1];
for(i in 1:n.cov)
  {
  covariates.row = covariates[i,];
  final.row = as.data.frame(t(rep("NA",37)),stringsAsFactors = FALSE);
  colnames(final.row) = tabularized.cols;
  final.row$`data_collector` = collector = covariates.row$`data_collector`;
  final.row$`person_id` = person = covariates.row$`person_id`;
  final.row[1,27:37] = covariates.row[3:13];
  
  subpanel = panel[panel$data_collector == collector & panel$person_id == person, ];
  n.sub = dim(subpanel)[1];
  for(j in 1:n.sub)
    {
    subpanel.row = subpanel[j,];
      s = subpanel.row$side;
      k = subpanel.row$mkey;
      jk = paste0(k,"-",s);
      v = subpanel.row$mvalue;
    final.row$side = s;
    final.row[jk] = v;
  }
  tabularized.df = rbind(tabularized.df, final.row);
  
  }

collector = "7a7ad17163012c8f04322273aebfe886";
outfile = paste0(path.measure,"/","measure","-",collector,".txt");

utils::write.table( tabularized.df , file=outfile, quote=FALSE, col.names=TRUE, row.names=FALSE, sep="|");
```

```{r}

```

